// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsGVd4ydPn9X7tVK3T2Ijrr6OeDYqfAs',
    appId: '1:418738374879:web:10b0ebd5a24d2582df416a',
    messagingSenderId: '418738374879',
    projectId: 'fund-d8173',
    authDomain: 'fund-d8173.firebaseapp.com',
    storageBucket: 'fund-d8173.firebasestorage.app',
    measurementId: 'G-BCKB7R1KD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoh8gL8txVauRLL62KExgivWRxTaGMO54',
    appId: '1:418738374879:android:21b5fe8020a0403edf416a',
    messagingSenderId: '418738374879',
    projectId: 'fund-d8173',
    storageBucket: 'fund-d8173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwvOVPA6jxu5V5ouM78glA98ITTUb18TE',
    appId: '1:418738374879:ios:f1c8d1cb31658b9cdf416a',
    messagingSenderId: '418738374879',
    projectId: 'fund-d8173',
    storageBucket: 'fund-d8173.firebasestorage.app',
    iosBundleId: 'com.example.fundraising',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwvOVPA6jxu5V5ouM78glA98ITTUb18TE',
    appId: '1:418738374879:ios:f1c8d1cb31658b9cdf416a',
    messagingSenderId: '418738374879',
    projectId: 'fund-d8173',
    storageBucket: 'fund-d8173.firebasestorage.app',
    iosBundleId: 'com.example.fundraising',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzsGVd4ydPn9X7tVK3T2Ijrr6OeDYqfAs',
    appId: '1:418738374879:web:8b2969241d14ee69df416a',
    messagingSenderId: '418738374879',
    projectId: 'fund-d8173',
    authDomain: 'fund-d8173.firebaseapp.com',
    storageBucket: 'fund-d8173.firebasestorage.app',
    measurementId: 'G-2KTGL4H56W',
  );
}
